karrodeko/urls.py
from django.contrib import admin
from django.urls import path
import management.views
import authentication.views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', management.views.dashbord, name='dashbord'),
    path('login/', authentication.views.login_page, name='login'),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="authentication/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'), name='password_reset_complete'),      
    path('password_reset', authentication.views.password_reset_request, name="password_reset"),

    path('user/new', authentication.views.new_user_page, name='new_user_page'),
    path('customer/new', management.views.new_customer, name='new_customer'),
    path('customer/import', management.views.import_customer, name='import_customer'),
    path('customer/import/create/<int:client_id>/', management.views.import_to_create_customer, name='import_to_create_customer'),
    path('customer/<int:customer_id>/', management.views.info_customer, name='info_customer'),
    path('customer/<int:customer_id>/edit', management.views.edit_customer, name='edit_customer'),
    path('customer/<int:customer_id>/delete', management.views.delete_customer, name='delete_customer'),
    path('customer/<int:customer_id>/delete-confirmation', management.views.delete_customer_confirmation, name='delete_customer_confirmation'),
    path('customer/import/<int:client_id>/delete', management.views.delete_client, name='delete_client'),
    path('customer/import/<int:client_id>/delete-confirmation', management.views.delete_client_confirmation, name='delete_client_confirmation'),
    path('customer/<int:customer_id>/BDL', management.views.bon_de_livraison, name='bon_de_livraison'),
    path('customer/<int:customer_id>/en_cours/<int:statut>', management.views.en_cours, name='en_cours'),
    path('customer/<int:customer_id>/validation', management.views.validation, name='validation'),
    path('customer/<int:customer_id>/retour-atelier', management.views.retour_atelier, name='retour_atelier'),
    path('customer/<int:customer_id>/etiquette', management.views.etiquette, name='etiquette'),
    path('customer/<int:customer_id>/etiquette/impression', management.views.etiquette_impression, name='etiquette_impression'),
    path('customer/scanner', management.views.scanner, name='scanner'),
    path('customer/<int:customer_id>/BDL/mail/<int:bdl_id>/', management.views.send_bdl, name='send_bdl'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
handler404 = management.views.page_not_found_view

management/models.py
from django.db import models
from django.utils.translation import gettext_lazy  as _

#Status des customer
EN_ATTENTE = 1
EN_COURS_GRANITE = 2
EN_COURS_PLINTHE = 3
A_RECUPERER = 4
A_LIVRE = 5
TERMINE = 6

#Class qui gère les clients
class Clients(models.Model):
    nom = models.CharField(max_length=100, blank=True, default="", verbose_name='Nom')
    prenom = models.CharField(max_length=100, blank=True, default="", verbose_name='Prénom')
    numero = models.CharField(max_length=100, blank=True, default="", verbose_name='Numéro')
    email = models.EmailField(_('email address'), unique=False)
    email2 = models.EmailField(_('email address'), unique=False, blank=True, default="")

#Class qui gère les commandes
class Customer(models.Model):
    client = models.ForeignKey(Clients, on_delete=models.CASCADE, null=True)
    nom = models.CharField(max_length=100, blank=True, default="", verbose_name='Nom')
    prenom = models.CharField(max_length=100, blank=True, default="", verbose_name='Prénom')
    numero = models.CharField(max_length=100, blank=True, default="", verbose_name='Numéro')
    email = models.EmailField(_('email address'), unique=False)
    email2 = models.EmailField(_('email address'), unique=False, blank=True, default="")
    description = models.TextField(blank=True, verbose_name='Description')
    qr_path = models.CharField(max_length=500, blank=True)
    status = models.IntegerField(blank=True, default=1)
    to_deliver = models.BooleanField(default=False)
    signature_client_path = models.CharField(max_length=500, blank=True)
    signature_KD_path = models.CharField(max_length=500, blank=True)
    signature_client_commande_path = models.CharField(max_length=500, blank=True)
    date_commande = models.DateTimeField(auto_now_add=True, null=True)
    is_signed_commande = models.BooleanField(default=False)

    def get_description(self):
        return self.description.split(';')

#Class qui gère les bon de livraisons
class BDL(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date_livraison = models.DateTimeField(auto_now_add=True)
    is_signed_client = models.BooleanField(default=False)
    is_signed_KD = models.BooleanField(default=False)

management/forms.py
from django import forms
from . import models

#Formulaire de création d'un client
class CreateCustomerForm(forms.ModelForm):
    class Meta:
        model = models.Customer
        fields = ['nom', 'prenom', 'numero', 'email', 'email2', 'description', 'to_deliver']

#Formulaire de création d'un bon de livraison
class CreateSignatureForm(forms.Form):
    signature_client = forms.CharField(max_length = 1000, label='Signature Client')
    signature_KD = forms.CharField(max_length = 1000, label='Signature KARRO DEKO')

management/views.py
import base64
from django.shortcuts import render, redirect, get_object_or_404
from . import forms, models
import qrcode
from django.conf import settings
from django.urls import reverse
import os
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required, permission_required

from weasyprint import HTML
from datetime import date

from django.core.mail import EmailMessage
import shutil


#Dashbord
@login_required
def dashbord(request):
    customers = models.Customer.objects.all().order_by('-id')
    return render(request, 'management/dashbord.html', context={'list_customer': customers})

#Nouveau client
@login_required
def new_customer(request):
    form = forms.CreateCustomerForm()
    if request.method == 'POST':
        form = forms.CreateCustomerForm(request.POST)
        if form.is_valid():
            customer = form.save()

            clients = models.Clients.objects.all()
            save = True

            for c in clients :
                if customer.nom == c.nom and customer.prenom == c.prenom and customer.email == c.email and customer.email2 == c.email2 :
                    save = False
            if save :                
                client = models.Clients(nom=customer.nom, prenom=customer.prenom, numero=customer.numero, email=customer.email, email2=customer.email2)
                client.save()
                customer.client = client
            else :
                customer.client = get_object_or_404(models.Clients, nom=customer.nom, prenom=customer.prenom, numero=customer.numero, email=customer.email, email2=customer.email2)
            

            fichier = '/signature_client_commande.png';               
            directory = str(settings.BASE_DIR) + settings.MEDIA_URL + str(customer.id) + customer.nom + customer.prenom 
                    
            if os.path.isdir(directory) is False :
                os.makedirs(directory)

            signatureC = request.POST['signature_client_commande']
            if signatureC and os.path.isfile(os.path.join(directory, fichier)) is False :
                # enregistrer le fichier PNG
                image_sign = open(directory + fichier, 'w')
                with open(directory + fichier, "wb") as f:
                    f.write(base64.b64decode(signatureC.split(",")[1]))
                image_sign.close()
                
                customer.signature_client_commande_path = settings.MEDIA_URL + str(customer.id) + customer.nom + customer.prenom + fichier  

                customer.is_signed_commande = True
                customer.status = models.EN_ATTENTE
                
            customer.save()
            return redirect('etiquette', customer_id=customer.id)

    return render(request, 'management/new_customer.html', context={'form': form, 'date': date.today()})

#Import client
@login_required
def import_customer(request):
    clients = models.Clients.objects.all().order_by('nom')
    return render(request, 'management/import_customer.html', context={'clients': clients})

#Création aprés import client
@login_required
def import_to_create_customer(request, client_id):
    client = get_object_or_404(models.Clients, id=client_id)  
    new_customer = models.Customer(nom=client.nom, prenom=client.prenom, numero=client.numero, email=client.email, email2=client.email2)

    form = forms.CreateCustomerForm(instance=new_customer)
    if request.method == 'POST':
        form = forms.CreateCustomerForm(request.POST, instance=new_customer)
        if form.is_valid():
            customer = form.save()

            clients = models.Clients.objects.all()
            client_tmp = models.Clients(nom=customer.nom, prenom=customer.prenom, numero=customer.numero, email=customer.email, email2=customer.email2)
            save = True
            for c in clients :
                if client_tmp.nom == c.nom and client_tmp.prenom == c.prenom and client_tmp.email == c.email and client_tmp.email2 == c.email2 :
                    save = False
            if save :
                client_tmp.save()
                customer.client = client_tmp
            else :
                customer.client = client

            fichier = '/signature_client_commande.png';               
            directory = str(settings.BASE_DIR) + settings.MEDIA_URL + str(customer.id) + customer.nom + customer.prenom 
                    
            if os.path.isdir(directory) is False :
                os.makedirs(directory)

            signatureC = request.POST['signature_client_commande']
            if signatureC and os.path.isfile(os.path.join(directory, fichier)) is False :
                # enregistrer le fichier PNG
                image_sign = open(directory + fichier, 'w')
                with open(directory + fichier, "wb") as f:
                    f.write(base64.b64decode(signatureC.split(",")[1]))
                image_sign.close()
                
                customer.signature_client_commande_path = settings.MEDIA_URL + str(customer.id) + customer.nom + customer.prenom + fichier  

                customer.is_signed_commande = True
        
            
            customer.save()
            return redirect('etiquette', customer_id=customer.id)
        
    return render(request, 'management/new_customer_import.html', context={'form': form, 'date': date.today()})

#Modifier client
@login_required
def edit_customer(request, customer_id):
    customer = get_object_or_404(models.Customer, id=customer_id)  
    client = get_object_or_404(models.Clients, id=customer.client.id)   
    descriptions = customer.get_description()
    form = forms.CreateCustomerForm(instance=customer)
    if request.method == 'POST':
        form = forms.CreateCustomerForm(request.POST, instance=customer)
        if form.is_valid():

            customer = form.save()
            
            client.nom = customer.nom
            client.prenom = customer.prenom
            client.numero = customer.numero
            client.email = customer.email
            client.email2 = customer.email2
            client.save()
            
            fichier = '/signature_client_commande.png';               
            directory = str(settings.BASE_DIR) + settings.MEDIA_URL + str(customer.id) + customer.nom + customer.prenom 
                    
            if os.path.isdir(directory) is False :
                os.makedirs(directory)

            signatureC = request.POST['signature_client_commande']
            if signatureC and os.path.isfile(os.path.join(directory, fichier)) is False :
                # enregistrer le fichier PNG
                image_sign = open(directory + fichier, 'w')
                with open(directory + fichier, "wb") as f:
                    f.write(base64.b64decode(signatureC.split(",")[1]))
                image_sign.close()
                
                customer.signature_client_commande_path = settings.MEDIA_URL + str(customer.id) + customer.nom + customer.prenom + fichier  

                customer.is_signed_commande = True
                customer.save()
        
            
            return redirect('etiquette', customer_id=customer.id)
        
    return render(request, 'management/edit_customer.html', context={'form': form, 'customer': customer, 'descriptions': descriptions})

#Supprimer Customer
@login_required
def delete_customer(request, customer_id):
    customer = get_object_or_404(models.Customer, id=customer_id)
    directory = str(settings.BASE_DIR) + settings.MEDIA_URL + str(customer.id) + customer.nom + customer.prenom
    if os.path.exists(directory):
        shutil.rmtree(directory)
    customer.delete()
    customers = models.Customer.objects.all().order_by('-id')
    return render(request, 'management/dashbord.html', context={'list_customer': customers})

#Confirmation de suppression Customer
@login_required
def delete_customer_confirmation(request, customer_id):
    customer = get_object_or_404(models.Customer, id=customer_id)
    return render(request, 'management/delete_customer.html', context={'customer': customer})  

#Supprimer client
@login_required
def delete_client(request, client_id):
    client = get_object_or_404(models.Clients, id=client_id)
    client.delete()
    clients = models.Clients.objects.all().order_by('nom')
    return render(request, 'management/import_customer.html', context={'clients': clients})

#Confirmation de suppression client
@login_required
def delete_client_confirmation(request, client_id):
    client = get_object_or_404(models.Clients, id=client_id)
    return render(request, 'management/delete_client.html', context={'client': client})   

#Info du client
@login_required
def info_customer(request, customer_id):
    customer = get_object_or_404(models.Customer, id=customer_id)
    descriptions = customer.get_description()
    return render(request, 'management/info_customer.html', context={'customer': customer, 'descriptions': descriptions})

#Bon de commande    
@login_required
def bon_de_livraison(request, customer_id):
    customer = get_object_or_404(models.Customer, id=customer_id)
    descriptions = customer.get_description()
    if models.BDL.objects.filter(customer=customer).exists():
        bdl = models.BDL.objects.filter(customer=customer)
        bdl = bdl[0]
    else:
        bdl = models.BDL(customer=customer)
        bdl.save()

    form = forms.CreateSignatureForm()
    if request.method == 'POST':
        form = forms.CreateSignatureForm(request.POST)
        fichierC = '/signature_client.png';    
        fichierK = '/signature_KD.png';               
        directory = str(settings.BASE_DIR) + settings.MEDIA_URL + str(customer.id) + customer.nom + customer.prenom 
                
        if os.path.isdir(directory) is False :
            os.makedirs(directory)

        signatureC = request.POST['signature_client']
        signatureK = request.POST['signature_KD']
        if signatureC or signatureK:    

management/templates/management/bdc.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="info-bdc">

    </div>
    <div class="signature">

    </div>

    <div class="button-bdc">
        <a href="{% url 'edit_customer' customer_id %}">
            <div class="button-element">
                <p>Envoyer</p>
            </div>
        </a>
    </div>

{% endblock %}

management/templates/management/delete_client.html
{% extends 'base.html' %}
{% block content %}
  <div class="delete">
    <h1>Etes-vous sûr de vouloir supprimer le client : <br>{{ client.nom }} {{ client.prenom }} ?</h1>
    <form method="post">
        {% csrf_token %}

        <div class="info-delete-submit">
            <a href="{% url 'delete_client' client.id  %}">
              <div class="info-delete-button">
                Oui
              </div>
            </a>
            <a href="{% url 'import_customer'  %}">
              <div class="info-delete-button">
                Non
              </div>
            </a>
        </div> 
    </form>
  </div>
{% endblock %}

management/templates/management/delete_customer.html
{% extends 'base.html' %}
{% block content %}
  <div class="delete">
    <h1>Etes-vous sûr de vouloir supprimer le client : <br>{{ customer.nom }} {{ customer.prenom }} ?</h1>
    <form method="post">
        {% csrf_token %}

        <div class="info-delete-submit">
            <a href="{% url 'delete_customer' customer.id  %}">
              <div class="info-delete-button">
                Oui
              </div>
            </a>
            <a href="{% url 'info_customer' customer.id  %}">
              <div class="info-delete-button">
                Non
              </div>
            </a>
        </div> 
    </form>
  </div>
{% endblock %}

management/templates/management/edit_customer.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    .add-desc {
        background-color: #cccccc;
        border: none;
        padding: 5px;
        text-align: center;
        color: #ffffff;
        border-radius: 10px;
        font-size: 30px;
        font-weight: bold;
    }

/* The container */
.container {
    display: block;
    position: relative;
    padding-left: 35px;
    margin-bottom: 12px;
    cursor: pointer;
    font-size: 22px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}

/* Hide the browser's default checkbox */
.container input {
    position: absolute;
    opacity: 0;
    cursor: pointer;
    height: 0;
    width: 0;
}

/* Create a custom checkbox */
.checkmark {
    position: absolute;
    top: 0;
    left: 0;
    height: 25px;
    width: 25px;
    background-color: #fff;
    border: solid 1px black;
}

/* On mouse-over, add a grey background color */
.container:hover input ~ .checkmark {
    background-color: #ccc;
}

/* When the checkbox is checked, add a blue background */
.container input:checked ~ .checkmark {
    background-color: #830000;
}

/* Create the checkmark/indicator (hidden when not checked) */
.checkmark:after {
    content: "";
    position: absolute;
    display: none;
}

/* Show the checkmark when checked */
.container input:checked ~ .checkmark:after {
    display: block;
}

/* Style the checkmark/indicator */
.container .checkmark:after {
    left: 9px;
    top: 5px;
    width: 5px;
    height: 10px;
    border: solid white;
    border-width: 0 3px 3px 0;
    -webkit-transform: rotate(45deg);
    -ms-transform: rotate(45deg);
    transform: rotate(45deg);
}
</style>
{% endblock %}

{% block content %}

<a href="{% url 'info_customer' customer.id %}"><div class="arrow-back"></div></a>

<div class="form-cust">
    <form method="post" id="id-form-cust">
        <div class="form-content">
            <label for="id_nom">Nom</label>{{ form.nom }}
        </div>
        <div class="form-content">
            <label for="id_prenom">Prenom</label>{{ form.prenom }}
        </div>
        <div class="form-content">
            <label for="id_numero">Numéro</label>{{ form.numero }}
        </div>
        <div class="form-content">
            <label for="id_email">Email</label>{{ form.email }}
        </div>
        <div class="form-content">
            <label for="id_email">Email 2</label>{{ form.email2 }}
        </div>
        <br><br>
        <div class="form-content">
            <label class="container">En livraison
                {{ form.to_deliver }}
                <span class="checkmark"></span>
            </label>
        </div>
        <br><br>
        <div class="form-content">
            <label for="id_description">Description</label>
            <div id="list-input-desc">
                {% for description in descriptions %}    
                    <input type="text" name="desc_{{ forloop.counter }}" maxlength="500" id="id_desc_{{ forloop.counter }}" value="{{ description }}">
                {% endfor %}
            </div>
            <div class="add-desc" id="id-add-desc">+</div>
        </div>
        {{ form.description }}
        <br><br>
        <div class="signature">
            <label>Date: &nbsp;&nbsp;{{ customer.date_commande|date:"d-m-Y" }}</label>       
            <br><br>
            {% if not customer.is_signed_commande %}
                <label>Signature Client: </label>
                <div class="bdl-signature">
                    <div class="signature-cadre"  id="signatureC"></div>
                    <a class="clearCanvas" id="clearCanvasC" onclick="clearSignatureC()" >Effacer</a>
                </div> 
            {% else %}   
                <br><br>
                <div class="signature-img" style="text-align: center;">
                    <label>Signature Client</label>
                    <img class="signature-img-cont" src="{{ customer.signature_client_commande_path }}"> 
                </div>
            {% endif %}            
        </div>
        <input type="text" name="signature_client_commande" maxlength="1000" id="id_signature_client_commande" style="display: none;">
        {% csrf_token %}
        <p class="button-form"><input type="submit" name="commit" value="Enregistrer"></p> 
    </form>
</div>

{% endblock %}



{% block javascripts %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'admin/js/flashcanvas.js'%}"></script>
<script src="{% static 'admin/js/jSignature.min.js'%}"></script>
<script>

    function clearSignatureC() {
        $("#signatureC").jSignature("reset");
    }

    $(document).ready(function () {  
        let list = document.getElementById("id_description").value.split(';');
        let cptInput = list.length; 
        const inputContainer = document.getElementById("list-input-desc");
        let descList = [];

        var signatureC_id = document.getElementById("signatureC");

        for (let i = 0; i < inputContainer.children.length; i++) {
            descList.push(inputContainer.children[i]);
        }

        $("#id-add-desc").click(function() { 
            cptInput++;
            const input = document.createElement("input");
            input.type = "text";
            input.id = "id_desc_" + cptInput;
            input.name = "desc_" + cptInput;
            input.maxLength = 500;
            inputContainer.appendChild(input);
            descList.push(input);
        }); 

        var signatureC = $("#signatureC").jSignature({ 
            'color': '#000000',
            'background-color': '#ffffff',
            'decor-color': '#d0e3f0'
        });

        $("#id-form-cust").submit(function() {  
            const values = descList.map(function(input) {
                return input.value;
            });
            const valueString = values.join(";");
            $("#id_description").val(valueString);

            if (signatureC_id && $('#signatureC').jSignature('getData','base30')[1].length>1) {
                var signature_C_data = $('#signatureC').jSignature('getData', 'image');
                $("#id_signature_client_commande").val(signature_C_data);
            }
        }); 

        $("#id_description").hide();
    });
</script>

{% endblock %}

management/templates/management/new_customer.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    .add-desc {
        background-color: #cccccc;
        border: none;
        padding: 5px;
        text-align: center;
        color: #ffffff;
        border-radius: 10px;
        font-size: 30px;
        font-weight: bold;
    }

    /* The container */
    .container {
        display: block;
        position: relative;
        padding-left: 35px;
        margin-bottom: 12px;
        cursor: pointer;
        font-size: 22px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }

    /* Hide the browser's default checkbox */
    .container input {
        position: absolute;
        opacity: 0;
        cursor: pointer;
        height: 0;
        width: 0;
    }

    /* Create a custom checkbox */
    .checkmark {
        position: absolute;
        top: 0;
        left: 0;
        height: 25px;
        width: 25px;
        background-color: #fff;
        border: solid 1px black;
    }

    /* On mouse-over, add a grey background color */
    .container:hover input ~ .checkmark {
        background-color: #ccc;
    }

    /* When the checkbox is checked, add a blue background */
    .container input:checked ~ .checkmark {
        background-color: #830000;
    }

    /* Create the checkmark/indicator (hidden when not checked) */
    .checkmark:after {
        content: "";
        position: absolute;
        display: none;
    }

    /* Show the checkmark when checked */
    .container input:checked ~ .checkmark:after {
        display: block;
    }

    /* Style the checkmark/indicator */
    .container .checkmark:after {
        left: 9px;
        top: 5px;
        width: 5px;
        height: 10px;
        border: solid white;
        border-width: 0 3px 3px 0;
        -webkit-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        transform: rotate(45deg);
    }
</style>
{% endblock %}

{% block content %}

<a href="{% url 'dashbord' %}"><div class="arrow-back"></div></a>

<div class="form-cust">
    {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% for field_errors in form.errors.values %}
                    {% for error in field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <form method="post" id="id-form-cust">
        <div class="form-content">
            <label for="id_nom">Nom</label>{{ form.nom }}
        </div>
        <div class="form-content">
            <label for="id_prenom">Prenom</label>{{ form.prenom }}
        </div>
        <div class="form-content">
            <label for="id_numero">Numéro</label>{{ form.numero }}
        </div>
        <div class="form-content">
            <label for="id_email">Email</label>{{ form.email }}
        </div>
        <div class="form-content">
            <label for="id_email">Email 2</label>{{ form.email2 }}
        </div>
        <br><br>
        <div class="form-content">
            <label class="container">En livraison
                {{ form.to_deliver }}
                <span class="checkmark"></span>
            </label>
        </div>
        <br><br>
        <div class="form-content">
            <label for="id_description">Description</label>
            <div id="list-input-desc">
                <input type="text" name="desc_1" maxlength="500" id="id_desc_1">
            </div>
            <div class="add-desc" id="id-add-desc">+</div>
        </div>
        {{ form.description }}
        <br><br>
        <div class="signature">
            <label>Date: </label>{{ date|date:"d-m-Y" }}   
            <br><br>
            <label>Signature Client: </label>
            <div class="bdl-signature">
                <div class="signature-cadre"  id="signatureC"></div>
                <a class="clearCanvas" id="clearCanvasC" onclick="clearSignatureC()" >Effacer</a>
            </div>         
        </div>
        <input type="text" name="signature_client_commande" maxlength="1000" id="id_signature_client_commande" style="display: none;">
        {% csrf_token %}
        <p class="button-form"><input type="submit" name="commit" value="Enregistrer"></p> 
    </form>
</div>

{% endblock %}

{% block javascripts %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'admin/js/flashcanvas.js'%}"></script>
<script src="{% static 'admin/js/jSignature.min.js'%}"></script>
<script>

    function clearSignatureC() {
        $("#signatureC").jSignature("reset");
    }

    $(document).ready(function () {  
        let cptInput = 1; 
        const inputContainer = document.getElementById("list-input-desc");
        const input_first = document.getElementById("id_desc_1");
        let descList = [input_first];

        var signatureC_id = document.getElementById("signatureC");

        $("#id-add-desc").click(function() { 
            cptInput++;
            const input = document.createElement("input");
            input.type = "text";
            input.id = "id_desc_" + cptInput;
            input.name = "desc_" + cptInput;
            input.maxLength = 500;
            inputContainer.appendChild(input);
            descList.push(input);
        }); 

        var signatureC = $("#signatureC").jSignature({ 
            'color': '#000000',
            'background-color': '#ffffff',
            'decor-color': '#d0e3f0'
        });

        $("#id-form-cust").submit(function() {  
            const values = descList.map(function(input) {
                return input.value;
            });
            const valueString = values.join(";");
            $("#id_description").val(valueString);

            if (signatureC_id && $('#signatureC').jSignature('getData','base30')[1].length>1) {
                var signature_C_data = $('#signatureC').jSignature('getData', 'image');
                $("#id_signature_client_commande").val(signature_C_data);
            }
        }); 

        
        $("#id_description").hide();
    });
</script>

{% endblock %}